"""
Tests for devguardian/tools/debugger.py
Generated by TDD Auto-Pilot — fixed to match actual ask_gemini call signature.
ask_gemini(prompt, system_instruction=...) uses keyword arg, not positional.
"""

from unittest.mock import patch
from devguardian.tools.debugger import debug_error


@patch("devguardian.tools.debugger.ask_gemini")
@patch("devguardian.tools.debugger.build_project_context")
def test_debug_error_with_project_path(mock_build_project_context, mock_ask_gemini):
    """Project context is built and injected into the prompt."""
    mock_build_project_context.return_value = "Mocked Project Context"
    mock_ask_gemini.return_value = "Mocked Gemini Response"

    result = debug_error(
        error_message="TypeError: 'NoneType' object is not subscriptable",
        stack_trace="File 'main.py', line 10\n  print(x.lower())",
        code_snippet="x = None\nprint(x.lower())",
        language="Python",
        project_path="/path/to/project",
    )

    assert result == "Mocked Gemini Response"
    mock_build_project_context.assert_called_once_with("/path/to/project", "x = None\nprint(x.lower())")
    mock_ask_gemini.assert_called_once()
    # Verify prompt contents
    prompt = mock_ask_gemini.call_args[0][0]
    assert "Mocked Project Context" in prompt
    assert "TypeError" in prompt
    assert "Language: Python" in prompt
    # Verify system_instruction was passed as keyword arg
    assert mock_ask_gemini.call_args.kwargs.get("system_instruction") is not None


@patch("devguardian.tools.debugger.ask_gemini")
@patch("devguardian.tools.debugger.build_project_context")
def test_debug_error_without_project_path(mock_build_project_context, mock_ask_gemini):
    """Without project_path, build_project_context should never be called."""
    mock_ask_gemini.return_value = "Mocked Gemini Response"

    result = debug_error(
        error_message="ValueError: invalid literal for int()",
        stack_trace="File 'app.py', line 5",
        code_snippet="num = int('abc')",
        language="Python",
    )

    assert result == "Mocked Gemini Response"
    mock_build_project_context.assert_not_called()
    mock_ask_gemini.assert_called_once()
    prompt = mock_ask_gemini.call_args[0][0]
    assert "ValueError" in prompt
    assert "Language: Python" in prompt


@patch("devguardian.tools.debugger.ask_gemini")
def test_debug_error_minimal(mock_ask_gemini):
    """Only error_message is required; no stack trace or code in prompt."""
    mock_ask_gemini.return_value = "Mocked Gemini Response"

    result = debug_error("KeyError: 'missing_key'")

    assert result == "Mocked Gemini Response"
    mock_ask_gemini.assert_called_once()
    prompt = mock_ask_gemini.call_args[0][0]
    assert "KeyError" in prompt
    # Stack trace and code sections should be absent
    assert "Stack Trace" not in prompt
    assert "Code That Caused the Error" not in prompt


@patch("devguardian.tools.debugger.ask_gemini")
def test_debug_error_empty_language_omits_hint(mock_ask_gemini):
    """Empty language string should NOT add 'Language:' to the prompt."""
    mock_ask_gemini.return_value = "Mocked Gemini Response"

    result = debug_error(
        error_message="IndexError: list index out of range",
        stack_trace="File 'data.py', line 20",
        code_snippet="my_list = [1, 2, 3]\nprint(my_list[10])",
        language="",
    )

    assert result == "Mocked Gemini Response"
    prompt = mock_ask_gemini.call_args[0][0]
    assert "IndexError" in prompt
    assert "Language:" not in prompt